config/routes.rb
EsportsphDota::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :matches do
    member do
      get 'edit_stats'
      patch 'update_competing_players'
    end
  end

  resources :player_stats

  resources :teams

  get 'rivalries' => 'rivalries#show', as: 'rivalry'
  get 'rivalries/select' => 'rivalries#select', as: 'select_rivalry'

  root 'matches#index'

end

app/controllers/rivalries_controller.rb
class RivalriesController < ApplicationController

  def select

  end

  def show
    team_1 = Team.find(params[:team_1])
    team_2 = Team.find(params[:team_2])
    @rivalry = Rivalry.find(team_1, team_2)
  end

end

app/views/rivalries/select.haml
= form_tag rivalry_path, method: 'get' do
  = select_tag :team_1, options_for_select(Team.all.collect{|x| [x.name, x.id]})
  = select_tag :team_2, options_for_select(Team.all.map{|x| [x.name, x.id]})
  = submit_tag "Go"

app/views/rivalries/show.haml
.row-fluid
  .span5.text-center
    %h1= @rivalry.team_1.name
    %h2= @rivalry.team_1.wins

  .span2.text-center

  .span5.text-center
    %h1= @rivalry.team_2.name
    %h2= @rivalry.team_2.wins

%h3.text-center Stats

.row-fluid
  .span5.text-center
    %h4= @rivalry.team_1.current_average_apm
  .span2.text-center
    %h4 APM
  .span5.text-center
    %h4= @rivalry.team_2.current_average_apm

.row-fluid
  .span5.text-center
    %h4= @rivalry.team_1.current_average_gold
  .span2.text-center
    %h4 Ave Gold
  .span5.text-center
    %h4= @rivalry.team_2.current_average_gold

.row-fluid
  .span5.text-center
    %h4= @rivalry.team_1.current_average_kills
  .span2.text-center
    %h4 Ave Kills
  .span5.text-center
    %h4= @rivalry.team_2.current_average_kills

.row-fluid
  .span5.text-center
    %h4= @rivalry.team_1.current_average_deaths
  .span2.text-center
    %h4 Ave Deaths
  .span5.text-center
    %h4= @rivalry.team_2.current_average_deaths

.row-fluid
  .span5.text-center
    %h4= @rivalry.team_1.current_average_assists
  .span2.text-center
    %h4 Ave Assists
  .span5.text-center
    %h4= @rivalry.team_2.current_average_assists

%hr

%h3.text-center Overall Stats

.row-fluid
  .span5.text-center
    %h4= @rivalry.team_1.historical_average_apm
  .span2.text-center
    %h4 APM
  .span5.text-center
    %h4= @rivalry.team_2.historical_average_apm

.row-fluid
  .span5.text-center
    %h4= @rivalry.team_1.historical_average_gold
  .span2.text-center
    %h4 Ave Gold
  .span5.text-center
    %h4= @rivalry.team_2.historical_average_gold

.row-fluid
  .span5.text-center
    %h4= @rivalry.team_1.historical_average_kills
  .span2.text-center
    %h4 Ave Kills
  .span5.text-center
    %h4= @rivalry.team_2.historical_average_kills

.row-fluid
  .span5.text-center
    %h4= @rivalry.team_1.historical_average_deaths
  .span2.text-center
    %h4 Ave Deaths
  .span5.text-center
    %h4= @rivalry.team_2.historical_average_deaths

.row-fluid
  .span5.text-center
    %h4= @rivalry.team_1.historical_average_assists
  .span2.text-center
    %h4 Ave Assists
  .span5.text-center
    %h4= @rivalry.team_2.historical_average_assists