config/routes.rb
EsportsphDota::Application.routes.draw do
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :matches do
    member do
      get 'edit_stats'
      patch 'update_competing_players'
    end
  end

  resources :player_stats

  resources :teams

  get 'rivalries' => 'rivalries#show', as: 'rivalry'
  get 'rivalries/select' => 'rivalries#select', as: 'select_rivalry'

  root 'matches#index'

end

app/models/match.rb
class Match < ActiveRecord::Base
  #habtm mapping
  has_many :team_matches
  has_many :player_stats
  accepts_nested_attributes_for :team_matches
  accepts_nested_attributes_for :player_stats

  has_many :hero_bans

  has_many :teams, through: :team_matches
  has_many :players, through: :player_stats

  belongs_to :winner, class_name: 'Team', foreign_key: :winning_team_id

  validates :name, :winning_team_id, presence: true

  validate :no_duplicate_teams

  def no_duplicate_teams
    # quick hack to check team is unique
    if self.team_matches.size != self.team_matches.collect(&:team_id).uniq.size
      self.errors[:teams] << "duplicate team"
      return false
    end
  end

  rails_admin do
    edit do
      field :name
      field :winner
      field :teams
    end
  end

  def team_1
    teams.first
  end

  def team_2
    teams.last
  end

end

# == Schema Information
#
# Table name: matches
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  winning_team_id :integer
#  created_at      :datetime
#  updated_at      :datetime
#  duration        :integer          default(0)
#

app/controllers/matches_controller.rb
class MatchesController < ApplicationController

  def index
    @matches = Match.all
  end

  def new
    @match = Match.new
    @match.team_matches.build
    @match.team_matches.build
  end

  def edit_stats
    @match = Match.find(params[:id])
    @team_1_player_stats = @match.player_stats.where(team: @match.team_1)

    @team_2_player_stats = @match.player_stats.where(team: @match.team_2)
  end

  def create
    @match = Match.new(match_params)
    if @match.save
      redirect_to edit_stats_match_path(@match)
    else
      render 'new'
    end
  end

  def edit
    @match = Match.find(params[:id])
    render 'new'
  end

  def update
    @match = Match.find(params[:id])
    if @match.update_attributes(match_params)
      redirect_to matches_path
    else
      render 'new'
    end
  end

  private

  def match_params
    params.require(:match).permit(:name,
                                  :duration,
                                  :winning_team_id,
                                  team_matches_attributes: [:team_id],
                                 )
  end

end

app/helpers/match_helper.rb
module MatchHelper
  def display_duration(seconds)
    Time.at(seconds.to_i).utc.strftime("%H:%M:%S")
  end
end

app/views/matches/_form.haml
= form_for match do |f|
  = f.label 'Match Name'
  = f.text_field :name

  = f.label 'Duration'
  = f.text_field :duration

  = f.label 'Winner'
  = f.select :winning_team_id, Team.all.map{|x| [x.name, x.id] }

  %br
  Teams
  #team-matches-fields
    %ul
    = f.fields_for :team_matches do |ff|
      %li= ff.select :team_id, Team.all.map{|x| [x.name, x.id] }

  %br
  = f.submit "Save"

app/views/matches/_player_match_fields.haml
%div{id: modal_id, class: 'modal hide fade', tab_index: '-1', role: 'dialog'}
  .modal-header
    %button.close{ data: {dismiss: "modal"}, aria: {hidden: 'true'} }
    %h3 Player Entry for #{representative.team.name}

  = form_for representative do |f|
    .modal-body
      = f.hidden_field :team_id
      = f.hidden_field :match_id

      %h4 General Stats
      .form-horizontal
        .control-group
          %label.control-label Player
          .controls
            = f.select :player_id, team.players.collect{|x| [x.name, x.id] }

        .control-group
          %label.control-label Hero
          .controls
            = f.select :hero_id, Hero.all.collect{|x| [x.name, x.id] }

        .control-group
          %label.control-label Kills
          .controls
            = f.text_field :kills

        .control-group
          %label.control-label Deaths
          .controls
            = f.text_field :deaths

        .control-group
          %label.control-label Assists
          .controls
            = f.text_field :assists

        .control-group
          %label.control-label Gold
          .controls
            = f.text_field :gold

        .control-group
          %label.control-label APM
          .controls
            = f.text_field :apm

      %h4 Farm Stats
      .form-horizontal
        .control-group
          %label.control-label Creep Kills
          .controls
            = f.text_field :creep_kills

        .control-group
          %label.control-label Creep Denies
          .controls
            = f.text_field :creep_denies

    .modal-footer
      = link_to "Close", '#', class: 'btn', data: { dismiss: 'modal' }
      = f.submit("Save Changes", class: 'btn btn-primary')

app/views/matches/_player_stat_fields.haml
%div{id: modal_id, class: 'modal hide fade', tab_index: '-1', role: 'dialog'}
  .modal-header
    %button.close{ data: {dismiss: "modal"}, aria: {hidden: 'true'} }
    %h3 Player Entry for #{representative.team.name}

  = form_for representative do |f|
    .modal-body
      = f.hidden_field :team_id
      = f.hidden_field :match_id

      %h4 General Stats
      .form-horizontal
        .control-group
          %label.control-label Player
          .controls
            = f.select :player_id, team.players.collect{|x| [x.name, x.id] }

        .control-group
          %label.control-label Hero
          .controls
            = f.select :hero_id, Hero.all.collect{|x| [x.name, x.id] }

        .control-group
          %label.control-label Kills
          .controls
            = f.text_field :kills

        .control-group
          %label.control-label Deaths
          .controls
            = f.text_field :deaths

        .control-group
          %label.control-label Assists
          .controls
            = f.text_field :assists

        .control-group
          %label.control-label Gold
          .controls
            = f.text_field :gold

        .control-group
          %label.control-label Strength
          .controls
            = f.text_field :strength

        .control-group
          %label.control-label Intelligence
          .controls
            = f.text_field :intelligence

        .control-group
          %label.control-label Vitality
          .controls
            = f.text_field :vitality

        .control-group
          %label.control-label XP Earned
          .controls
            = f.text_field :experience

        .control-group
          %label.control-label APM
          .controls
            = f.text_field :apm

      %h4 Farm Stats
      .form-horizontal
        .control-group
          %label.control-label Creep Kills
          .controls
            = f.text_field :creep_kills

        .control-group
          %label.control-label Creep Denies
          .controls
            = f.text_field :creep_denies

    .modal-footer
      = link_to "Close", '#', class: 'btn', data: { dismiss: 'modal' }
      = f.submit("Save Changes", class: 'btn btn-primary')

app/views/matches/_players_stats.haml
%table.table
  %tr
    %th Player Name
    %th Hero
    %th K/D/A
    %th CK/CD
    %th Gold
    %th S/I/V
    %th Experience
    %th APM
    %th Actions
  - player_stats.each do |player_stat|
    %tr
      %td= player_stat.player.name
      %td= player_stat.hero.name if player_stat.hero
      %td  #{player_stat.kills.to_i}/#{player_stat.deaths.to_i}/#{player_stat.assists.to_i}
      %td  #{player_stat.creep_kills.to_i}/#{player_stat.creep_denies.to_i}
      %td= player_stat.gold
      %td #{player_stat.strength.to_i}/#{player_stat.intelligence.to_i}/#{player_stat.vitality.to_i}
      %td= player_stat.experience
      %td= player_stat.apm.to_i
      %td= link_to "Edit", "#edit#{player_stat.id}", role: "button", data: { toggle: "modal" }

app/views/matches/edit_roster.haml
.row
  .span12
    %h1 Match Results
    %h2 #{@match.name.titleize}

%hr

.row-fluid
  .span12
    #team_1_players
      %h4
        Team 1 : #{@match.team_1.name}
        - if @match.winner.eql?(@match.team_1)
          (W)

      = render 'players_stats', player_stats: @team_1_player_stats

      - @team_1_player_stats.each do |player_stat|
        = render 'player_stat_fields', modal_id: "edit#{player_stat.id}", representative: player_stat, team: @match.team_1

      #players_matches-fields
        = link_to "Add Team 1 Player", '#team1Modal', role: "button", data: { toggle: "modal" }
        = render 'player_stat_fields', modal_id: 'team1Modal', representative: @match.player_stats.build(team_id: @match.team_1.id), team: @match.team_1

    #team_2_players
      %h4
        Team 2 #{@match.team_2.name}
        - if @match.winner.eql?(@match.team_2)
          (W)

      = render 'players_stats', player_stats: @team_2_player_stats

      - @team_2_player_stats.each do |player_stat|
        = render 'player_stat_fields', modal_id: "edit#{player_stat.id}", representative: player_stat, team: @match.team_2

      #players_matches-fields
        = link_to "Add Team 2 Player", '#team2Modal', role: "button", data: { toggle: "modal" }
        = render 'player_stat_fields', modal_id: 'team2Modal', representative: @match.player_stats.build(team_id: @match.team_2.id), team: @match.team_2

app/views/matches/edit_stats.haml
.row
  .span12
    %h1 Match Results
    %h2 #{@match.name.titleize}

%hr

.row-fluid
  .span12
    #team_1_players
      %h4
        Team 1 : #{@match.team_1.name}
        - if @match.winner.eql?(@match.team_1)
          (W)

      = render 'players_stats', player_stats: @team_1_player_stats

      - @team_1_player_stats.each do |player_stat|
        = render 'player_stat_fields', modal_id: "edit#{player_stat.id}", representative: player_stat, team: @match.team_1

      #players_matches-fields
        = link_to "Add Team 1 Player", '#team1Modal', role: "button", data: { toggle: "modal" }
        = render 'player_stat_fields', modal_id: 'team1Modal', representative: @match.player_stats.build(team_id: @match.team_1.id), team: @match.team_1

    #team_2_players
      %h4
        Team 2 #{@match.team_2.name}
        - if @match.winner.eql?(@match.team_2)
          (W)

      = render 'players_stats', player_stats: @team_2_player_stats

      - @team_2_player_stats.each do |player_stat|
        = render 'player_stat_fields', modal_id: "edit#{player_stat.id}", representative: player_stat, team: @match.team_2

      #players_matches-fields
        = link_to "Add Team 2 Player", '#team2Modal', role: "button", data: { toggle: "modal" }
        = render 'player_stat_fields', modal_id: 'team2Modal', representative: @match.player_stats.build(team_id: @match.team_2.id), team: @match.team_2

app/views/matches/index.haml
.row-fluid
  .span12
    .content
      .actions
        = link_to "Create Match", new_match_path, class: 'btn btn-primary'

      .something
        %table.table
          %tr
            %th Match Name
            %th Teams
            %th Duration
            %th Actions
          - @matches.each do |match|
            %tr
              %td= match.name
              %td
                %strong #{match.team_1.name}
                - if match.winner == match.team_1
                  (W)
                vs
                %strong #{match.team_2.name}
                - if match.winner == match.team_2
                  (W)
              %td= display_duration(match.duration.to_i)

              %td
                = link_to "Edit Match", edit_match_path(match), class: 'btn btn-default'
                = link_to "Edit Match Stats", edit_stats_match_path(match), class: 'btn btn-default'

app/views/matches/new.haml
= render 'form', match: @match